version: '3.8'

services:

  node:
    # reminder, don't use latest tag in production, use versions created by CI/CD
    # image: bretfisher/node-docker-good-defaults:latest
    # build: 
      # context: .
    image: jonty99/vrp-backend-node:latest
    command: node /opt/node_app/app/server.js
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URL_FILE=/run/secrets/mongo_url
      - MONGO_USERNAME_FILE=/run/secrets/mongo_root
      - MONGO_PASSWORD_FILE=/run/secrets/mongo_root_password
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE_NAME=exampleDb
    secrets:
      - mongo_url
      - mongo_root
      - mongo_root_password
    deploy:
      replicas: 1

  mongo:
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongo_root
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_root_password
      - MONGO_INITDB_DATABASE=exampleDb
    secrets:
      - mongo_root
      - mongo_root_password
    volumes:
      - mongodata:/data/db
      # - ./mongod.conf:/etc/mongod.conf:ro
    deploy:
      placement:
        constraints:
          - node.role == manager
    healthcheck:
      test: "[ `echo 'db.runCommand(\"ping\").ok' | mongo localhost/exampleDb --quiet` ] && echo 0 || echo 1"
      interval: 5s
      timeout: 5s
      retries: 3

secrets:
  mongo_url:
    external: true
  mongo_root:
    external: true
  mongo_root_password:
    external: true

volumes:
  mongodata:
