version: '3.8'
# version 2.x allows you to use depends_on with conditions that cause
# the node app to wait on mongo to respond to a healthy healthcheck before node is started
# v3.x doesn't have this feature yet, and is only needed if you want to use Swarm

services:

  node:
    build:
      context: .
    networks:
      - backend_net

  mongo:
    image: mongo:4.4.6
    networks:
      - backend_net

networks:
  backend_net:
    name: backend_net
    driver: overlay
    attachable: true
